// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWLoKP1qz4l79as68cauhMatPGnilQ9sw',
    appId: '1:419143087841:web:2bca69c292221616ab29a0',
    messagingSenderId: '419143087841',
    projectId: 'physioone-74446',
    authDomain: 'physioone-74446.firebaseapp.com',
    storageBucket: 'physioone-74446.firebasestorage.app',
    measurementId: 'G-8QBXZCZQ2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFiwl54gxomWJoG2pES6qcsQv0v3_xboI',
    appId: '1:419143087841:android:6b9e5d627b23913bab29a0',
    messagingSenderId: '419143087841',
    projectId: 'physioone-74446',
    storageBucket: 'physioone-74446.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7QKJWmHZLZmIsUMJREg0uOi8AEcYb0d4',
    appId: '1:419143087841:ios:d09050b56d04dc0dab29a0',
    messagingSenderId: '419143087841',
    projectId: 'physioone-74446',
    storageBucket: 'physioone-74446.firebasestorage.app',
    iosBundleId: 'com.example.clinicManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7QKJWmHZLZmIsUMJREg0uOi8AEcYb0d4',
    appId: '1:419143087841:ios:d09050b56d04dc0dab29a0',
    messagingSenderId: '419143087841',
    projectId: 'physioone-74446',
    storageBucket: 'physioone-74446.firebasestorage.app',
    iosBundleId: 'com.example.clinicManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWLoKP1qz4l79as68cauhMatPGnilQ9sw',
    appId: '1:419143087841:web:7ab9cc2c00b8e1d4ab29a0',
    messagingSenderId: '419143087841',
    projectId: 'physioone-74446',
    authDomain: 'physioone-74446.firebaseapp.com',
    storageBucket: 'physioone-74446.firebasestorage.app',
    measurementId: 'G-P1TWV3B9P1',
  );
}
