// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNahSbzgQGMRd8vn9zsEV0pUNOcDKl5AQ',
    appId: '1:817174772167:web:b2e8a3f96104fda7b801e2',
    messagingSenderId: '817174772167',
    projectId: 'physioprimedatabase',
    authDomain: 'physioprimedatabase.firebaseapp.com',
    databaseURL: 'https://physioprimedatabase-default-rtdb.firebaseio.com',
    storageBucket: 'physioprimedatabase.firebasestorage.app',
    measurementId: 'G-6EQ1QJT2ES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-LjuWORu7a9pFpcipRqj3rRO9tMlbFv4',
    appId: '1:817174772167:android:e50d2171cb635fdfb801e2',
    messagingSenderId: '817174772167',
    projectId: 'physioprimedatabase',
    databaseURL: 'https://physioprimedatabase-default-rtdb.firebaseio.com',
    storageBucket: 'physioprimedatabase.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNahSbzgQGMRd8vn9zsEV0pUNOcDKl5AQ',
    appId: '1:817174772167:web:606ce315f4c86c8eb801e2',
    messagingSenderId: '817174772167',
    projectId: 'physioprimedatabase',
    authDomain: 'physioprimedatabase.firebaseapp.com',
    databaseURL: 'https://physioprimedatabase-default-rtdb.firebaseio.com',
    storageBucket: 'physioprimedatabase.firebasestorage.app',
    measurementId: 'G-39E33E15KC',
  );
}
