// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC7UMdiyQq9aeRvZ1uO4Aw-8v4ugpYlUo',
    appId: '1:587868941535:web:87dcfd9c614ef25ff98d6a',
    messagingSenderId: '587868941535',
    projectId: 'physio-prime',
    authDomain: 'physio-prime.firebaseapp.com',
    storageBucket: 'physio-prime.firebasestorage.app',
    measurementId: 'G-ZSXT74YE8D',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC7UMdiyQq9aeRvZ1uO4Aw-8v4ugpYlUo',
    appId: '1:587868941535:web:385b573b086a96fdf98d6a',
    messagingSenderId: '587868941535',
    projectId: 'physio-prime',
    authDomain: 'physio-prime.firebaseapp.com',
    storageBucket: 'physio-prime.firebasestorage.app',
    measurementId: 'G-8WJKCG5NRD',
  );
}
